using UnityEngine;

namespace FZFUI.Autogen
{
    [CreateAssetMenu(fileName = "AutogenSettings", menuName = "Autogen/Create", order = 0)]
    public class AutogenSettings : ScriptableObject
    {
        public string AutogenScriptsFolderPath = "Scripts/UI/Autogenerated";
        public string UIScriptsFolderPath = "Scripts/UI";
    }
}