using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using FZFUI.UI.Buttons;
using Sirenix.OdinInspector;
using UnityEditor;
using UnityEngine;

namespace FZFUI.UI.Autogen
{
    public class BaseAutogen : MonoBehaviour
    {
        [ButtonGroup("Auto")]
        [Button("Generate", ButtonSizes.Medium)]
        private void GenerateFields()
        {
            var concreteClass = GetConcreteClass();
            var namespaceName = concreteClass.GetType().Namespace;
            var components = new List<Component>();
            var innerComponents = concreteClass.GetComponents<Component>().Except(new[] { concreteClass });
            var usingNames = new List<string>();
            RecursivelyGetComponents(transform, components);

            var fields = new List<string>();
            CollectComponents(components, fields, usingNames, (component) => component.gameObject.name);
            CollectComponents(innerComponents, fields, usingNames, (component) => component.GetType().Name);

            usingNames = usingNames.Distinct().ToList();
            var fileName = $"{concreteClass.GetType().Name}Autogen";
            var code = $@"using UnityEngine;
{string.Join("\n", usingNames)}

namespace {namespaceName}
{{
    public partial class {concreteClass.GetType().Name}
    {{
        {string.Join("\n\t\t", fields)}
    }}
}}
";
            var path = $"{Application.dataPath}/Scripts/UI/Autogenerated/{fileName}.cs";
            EditorApplication.LockReloadAssemblies();
            File.WriteAllText(path, code);
            AssetDatabase.Refresh();
            EditorApplication.UnlockReloadAssemblies();
        }

        private static void CollectComponents(IEnumerable<Component> components, List<string> fields,
            List<string> usingNames, System.Func<Component, string> namingPattern)
        {
            foreach (var component in components)
            {
                var type = component.GetType();
                var usingName = !string.IsNullOrWhiteSpace(type.Namespace) 
                    ? $"using {type.Namespace};" 
                    : "";
                var fieldName = $"[SerializeField] private {type.Name} {namingPattern?.Invoke(component)};";
                fields.Add(fieldName);
                if (!usingNames.Contains(usingName))
                    usingNames.Add(usingName);
            }
        }

        private static void RecursivelyGetComponents(Transform parent, List<Component> components)
        {
            for (int i = 0; i < parent.childCount; i++)
            {
                var child = parent.GetChild(i);
                bool isAutomaticField = false;
                var component = child
                    .GetComponents<Component>()
                    .FirstOrDefault(x => x.GetType()
                        .IsSubclassOf(typeof(BaseAutogen)));

                component ??= child.GetComponents<Component>()
                    .FirstOrDefault(x => x is ISubscribableButton);

                isAutomaticField = component != null;

                component ??= child
                    .GetComponents<Component>()
                    .FirstOrDefault(x => x != x.transform
                                         && x.GetType() != typeof(CanvasRenderer));

                component ??= child.transform;
                components.Add(component);
                if (isAutomaticField)
                    continue;
                if (child.childCount > 0)
                    RecursivelyGetComponents(child, components);
            }
        }

        [ButtonGroup("Auto")]
        [Button("Assign", ButtonSizes.Medium)]
        private void AssignFields()
        {
            var concreteClass = GetConcreteClass();
            var components =
                new List<Component>(concreteClass.GetComponents<Component>().Except(new[] { concreteClass }));
            RecursivelyGetComponents(transform, components);

            foreach (var component in components)
            {
                var field = concreteClass.GetType().GetFields(BindingFlags.Instance | BindingFlags.NonPublic)
                    .FirstOrDefault(x =>
                        (x.Name == component.gameObject.name || x.Name == component.GetType().Name)
                        && x.FieldType.Name == component.GetType().Name);
                if (field == null)
                    continue;

                field.SetValue(concreteClass, component);
            }

            Debug.Log("Fields assigned");
        }

        private Component GetConcreteClass()
        {
            return gameObject.GetComponents<Component>()
                .First(x => x.GetType().IsSubclassOf(typeof(BaseAutogen)));
        }

        [MenuItem("GameObject/Create New UI", false, 10)]
        private static void CreateScript(MenuCommand menuCommand)
        {
            string scriptName = Selection.activeObject.name;
            var filePath = $"Assets/Scripts/UI/{scriptName}.cs";

            File.WriteAllText(filePath, $@"using FZFUI.UI.Autogen;

namespace UI
{{
    public interface I{scriptName}
    {{
    
    }}
    public partial class {scriptName}: BaseAutogen, I{scriptName}
    {{

    }}
}}");
            AssetDatabase.Refresh();
            var asset = AssetDatabase.LoadAssetAtPath(filePath, typeof(MonoScript));
            if (asset == null)
            {
                return;
            }

            var activeGameObject = Selection.activeGameObject;

            if (activeGameObject != null)
            {
                var script = asset as MonoScript;
                if (script == null)
                    return;

                activeGameObject.AddComponent(script.GetClass());
            }
        }
    }
}